---
- name: FIREWALLD - Generate Rule Lists
  set_fact:
    all: "{% set data = dict() %}\
          {% for action in ['add', 'remove'] %}\
            {{ data.update({action: {}}) }}\
            {% for type in dynamic_common_types %}\
              {% set common_list = [] %}\
              {% if item[type].get('common_profiles') %}\
                {% for profile in item[type].common_profiles %}\
                  {% if common[type].get(profile) %}\
                    {{ common_list.extend(common[type][profile]) }}\
                  {% endif %}\
                {% endfor %}\
              {% endif %}\
              {% if action == 'add' %}\
                {{ data[action].update({type: common_list + item[type].rules}) }}\
              {% elif action == 'remove' %}\
                {% set to_remove = ansible_facts.ansible_local.firewalld[item.zone][type] | default([]) | difference(common_list + item[type].rules) %}\
                {{ data[action].update({type: to_remove}) }}\
              {% endif %}\
            {% endfor %}\
          {% endfor %}\
          {% set remove_sources = ansible_facts.ansible_local.firewalld[item.zone]['sources'] | default([]) | difference(item.sources) %}\
          {{ data['remove'].update({'sources': remove_sources}) }}\
          {% set add_sources = item.get('sources', []) %}\
          {{ data['add'].update({'sources': add_sources}) }}\
          {{ data }}"
  register: fact_data
  when: item.name in lookup('ansible.builtin.vars', inventory_var)
  with_items: "{{ profiles }}"

# - debug:
#     msg: "{{ fact_data }}"