---
- name: Converge
  hosts: all
  vars:
    skip_prompts: True
    remove_ufw: False
    profiles:
      - name: public-test
        zone: public
        target: DROP
        ports:
          rules:
            - 53/udp
            - 123/udp
            - 1433/tcp
        services:
          rules:
            - dhcp
            - http
            - https
        rich_rules:
          rules: []
          common_profiles: [limited_ssh, icmp]
      - name: Ansible Patching
        zone: patching-source
        sources:
          - 10.0.0.15/32
          - 10.0.1.0/24
          - 10.0.2.16
        target: DROP
        ports:
          rules: []
        services:
          rules:
            - dhcp
            - ssh
        rich_rules:
          rules: []
          common_profiles: [icmp]
  pre_tasks:
    - name: Install Container Specific RedHat
      yum:
        name:
          - firewalld
          - iproute
          - python3
      when: ansible_os_family == 'RedHat'

    - name: Install ip
      apt:
        name: iproute2
      when: ansible_os_family == 'Debian'

  roles:
    - deitchi.firewalld
      
