---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - access
  # - name: rhel8
  #   image: registry.access.redhat.com/ubi8/ubi-init
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   capabilities:
  #     - SYS_ADMIN
  #   #command: "/usr/sbin/init"
  #   pre_build_image: true
  #   cgroupns_mode: host  ## <-- This is the line I added
  # - name: ubuntu-22.04
  #   image: geerlingguy/docker-ubuntu2204-ansible:latest
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  #   groups:
  #     - access
  # - name: ubuntu-20.04
  #   image: geerlingguy/docker-ubuntu2004-ansible:latest
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  #   groups:
  #     - access
  # - name: centos-7
  #   image: geerlingguy/docker-centos7-ansible:latest
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  #   groups:
  #     - access
provisioner:
  name: ansible
  inventory:
    group_vars:
      access:
        fwd_zone: ['public-ssh']
      web:
        fwd_zone: ['public-http']

verifier:
  name: ansible
